name: CI для Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Выкачка полной истории репозитория

      - name: Настройка JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

      - name: Сборка с Maven
      run: mvn clean install

      - name: Запуск тестов
      run: mvn test #Здесь запускаются ваши тесты. Убедитесь, что тесты находятся в правильной папке.